In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, RobustScaler

In [29]:
t_df = pd.read_csv("./data/merged_annuale_meteo_sunrise_filtrato15.csv", delimiter=";")

In [3]:
df = pd.read_csv("./data/comm_code_filtered.csv", delimiter=";")
df

,INV03_CommunicationCode,INV02_CommunicationCode,Cont_CommunicationCode,timestamp
0,60,60,60,2022-02-02 00:05:00
1,60,60,60,2022-02-02 00:10:00
2,60,60,60,2022-02-02 00:15:00
3,60,60,60,2022-02-02 00:20:00
4,60,60,60,2022-02-02 00:25:00
...,...,...,...,...
143425,0,0,0,2023-06-16 17:45:00
143426,0,0,0,2023-06-16 17:50:00
143427,0,0,0,2023-06-16 17:55:00
143428,0,0,0,2023-06-16 18:00:00
143429,0,0,0,2023-06-16 18:05:00

In [15]:
def print_unique(df):
    for col in df:
        if col != "timestamp":
            print(f"column {col} : {df[col].unique()}")

In [4]:
df.head()

tmp_df = pd.DataFrame()

for col in df:
    if all(key in col for key in "CommunicationCode"):
        #if all(k in col for k in "INV"):
        tmp_df[col] = df[col].copy()
    else:
        pass
tmp_df["timestamp"] = df["timestamp"].copy()

In [5]:
for col in tmp_df:
    if any(key in col for key in ["INV03", "INV02", "Cont", "timestamp"]):
        #if all(k in col for k in "INV"):
        pass
    else:
        tmp_df.drop(columns=col, inplace=True)

In [ ]:
df.drop(columns=["Unnamed: 0", "Unnamed: 0.1", "INV01_CommunicationCode"], inplace=True)
df.head()

In [4]:
print(df.INV02_CommunicationCode.unique())
print(df.INV03_CommunicationCode.unique())
print(df.Cont_CommunicationCode.unique())

dic = {0:0, 60:1}

[ 60   0 116]
[ 60   0 116]
[ 60 118   0]

'\ndf.replace({"INV02_CommunicationCode": dic}, inplace=True)\ndf.replace({"INV03_CommunicationCode": dic}, inplace=True)\ndf.replace({"Cont_CommunicationCode": dic}, inplace=True)\n'

In [5]:
feature_list = [
    "INV02_CommunicationCode_60",
    "INV02_CommunicationCode_116",
    "INV03_CommunicationCode_60",
    "INV03_CommunicationCode_116",
    "Cont_CommunicationCode_60",
    "Cont_CommunicationCode_118",
    "timestamp"
]
n_df = pd.DataFrame(0, index=np.arange(len(df)), columns=feature_list)

In [6]:
for col in df:
    if any(key in col for key in "INV"):
        for i,val in enumerate(df[col].values):
            if val == 60:
                n_df[f"{col}_60"].loc[i] = 60
            if val == 116:
                n_df[f"{col}_116"].loc[i] = 116
            
    elif col=="Cont_CommunicationCode":
        for i,val in enumerate(df[col].values):
            if val == 60:
                n_df[f"{col}_60"].loc[i] = 60
            if val == 118:
                n_df[f"{col}_118"].loc[i] = 118

In [9]:
n_df["timestamp"] = df["timestamp"]
n_df

,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118,timestamp
0,60,0,60,0,60,0,2022-02-02 00:05:00
1,60,0,60,0,60,0,2022-02-02 00:10:00
2,60,0,60,0,60,0,2022-02-02 00:15:00
3,60,0,60,0,60,0,2022-02-02 00:20:00
4,60,0,60,0,60,0,2022-02-02 00:25:00
...,...,...,...,...,...,...,...
143425,0,0,0,0,0,0,2023-06-16 17:45:00
143426,0,0,0,0,0,0,2023-06-16 17:50:00
143427,0,0,0,0,0,0,2023-06-16 17:55:00
143428,0,0,0,0,0,0,2023-06-16 18:00:00
143429,0,0,0,0,0,0,2023-06-16 18:05:00

In [16]:
print_unique(n_df)

column INV02_CommunicationCode_60 : [1 0]
column INV02_CommunicationCode_116 : [0 1]
column INV03_CommunicationCode_60 : [1 0]
column INV03_CommunicationCode_116 : [0 1]
column Cont_CommunicationCode_60 : [1 0]
column Cont_CommunicationCode_118 : [0 1]

In [10]:
dic = {0:0, 60:1, 118:1, 116:1}


for col in n_df:
    if any(key in col for key in "CommunicationCode"):
        n_df.replace({f"{col}": dic}, inplace=True)

In [70]:
n_df

,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118,timestamp
0,1,0,1,0,1,0,2022-02-02 00:05:00
1,1,0,1,0,1,0,2022-02-02 00:10:00
2,1,0,1,0,1,0,2022-02-02 00:15:00
3,1,0,1,0,1,0,2022-02-02 00:20:00
4,1,0,1,0,1,0,2022-02-02 00:25:00
...,...,...,...,...,...,...,...
143425,0,0,0,0,0,0,2023-06-16 17:45:00
143426,0,0,0,0,0,0,2023-06-16 17:50:00
143427,0,0,0,0,0,0,2023-06-16 17:55:00
143428,0,0,0,0,0,0,2023-06-16 18:00:00
143429,0,0,0,0,0,0,2023-06-16 18:05:00

In [20]:
def custom_aggregation(group):
    return 1 if any(group == 1) else 0

#n_df["timestamp"]=pd.to_datetime(n_df["timestamp"])
#n_df.set_index("timestamp", inplace=True)
resampled=n_df.resample("15T").apply(custom_aggregation)


#n_df=df["2022-06-08 00:00:00":]

In [22]:
print_unique(resampled)

column INV02_CommunicationCode_60 : [1 0]
column INV02_CommunicationCode_116 : [0 1]
column INV03_CommunicationCode_60 : [1 0]
column INV03_CommunicationCode_116 : [0 1]
column Cont_CommunicationCode_60 : [1 0]
column Cont_CommunicationCode_118 : [0 1]

In [23]:
n_df = resampled["2022-06-08 00:00:00":]
n_df

,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118
timestamp,,,,,,
2022-06-08 00:00:00,0,0,0,0,0,0
2022-06-08 00:15:00,0,0,0,0,0,0
2022-06-08 00:30:00,0,0,0,0,0,0
2022-06-08 00:45:00,0,0,0,0,0,0
2022-06-08 01:00:00,0,0,0,0,0,0
...,...,...,...,...,...,...
2023-06-16 17:00:00,0,0,0,0,0,0
2023-06-16 17:15:00,0,0,0,0,0,0
2023-06-16 17:30:00,0,0,0,0,0,0
2023-06-16 17:45:00,0,0,0,0,0,0
2023-06-16 18:00:00,0,0,0,0,0,0

In [26]:
print_unique(resampled["2022-06-08 00:00:00":])

column INV02_CommunicationCode_60 : [0 1]
column INV02_CommunicationCode_116 : [0]
column INV03_CommunicationCode_60 : [0 1]
column INV03_CommunicationCode_116 : [0]
column Cont_CommunicationCode_60 : [0 1]
column Cont_CommunicationCode_118 : [0 1]

In [12]:

t_df

,INV03_CurrentDC(A),INV03_CurrentAC(A),INV03_PowerAC(kW),INV03_PowerDC(kW),INV03_InternalTemperature(C),INV03_HeatSinkTemperature(C),INV03_VoltageDC(V),INV03_VoltageAC(V),INV02_CurrentDC(A),INV02_CurrentAC(A),...,month_sin,month_cos,relativehumidity_2m (%),dewpoint_2m (Â°C),rain (mm),cloudcover (%),soil_temperature_7_to_28cm (Â°C),soil_moisture_7_to_28cm (mÂ³/mÂ³),isday,timestamp
0,0.00000,0.00000,0.000000,0.00,0.000000,0.000000,0.0000,0.00000,0.00,0.00000,...,2.449294e-16,-2.0,140.0,35.800000,0.0,42.0,51.800000,0.364,0.0,2022-06-08 00:00:00
1,0.00000,0.00000,0.000000,0.00,0.000000,0.000000,0.0000,0.00000,0.00,0.00000,...,3.673941e-16,-3.0,210.0,53.699997,0.0,63.0,77.700000,0.546,0.0,2022-06-08 00:15:00
2,0.00000,0.00000,0.000000,0.00,0.000000,0.000000,0.0000,0.00000,0.00,0.00000,...,3.673941e-16,-3.0,210.0,53.699997,0.0,63.0,77.700000,0.546,0.0,2022-06-08 00:30:00
3,0.00000,0.00000,0.000000,0.00,0.000000,0.000000,0.0000,0.00000,0.00,0.00000,...,3.673941e-16,-3.0,210.0,53.699997,0.0,63.0,77.700000,0.546,0.0,2022-06-08 00:45:00
4,0.00000,0.00000,0.000000,0.00,0.000000,0.000000,0.0000,0.00000,0.00,0.00000,...,3.673941e-16,-3.0,219.0,52.800003,0.0,45.0,76.800000,0.546,0.0,2022-06-08 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35876,330.39000,378.76000,173.260000,185.38,29.096666,33.846670,1683.9800,797.70996,332.06,385.26000,...,3.673941e-16,-3.0,186.0,42.300003,0.0,135.0,62.699997,1.116,1.0,2023-06-16 17:00:00
35877,316.97998,379.22998,170.680000,182.93,29.443335,33.656666,1732.4400,784.90000,320.10,383.94000,...,3.673941e-16,-3.0,186.0,42.300003,0.0,135.0,62.699997,1.116,1.0,2023-06-16 17:15:00
35878,348.16998,415.06000,186.120000,198.87,29.236668,34.079998,1712.6799,780.74000,346.12,420.80000,...,3.673941e-16,-3.0,186.0,42.300003,0.0,135.0,62.699997,1.116,1.0,2023-06-16 17:30:00
35879,320.61000,369.75000,165.760000,177.50,29.343332,33.676666,1657.1499,781.56006,321.28,374.66998,...,3.673941e-16,-3.0,186.0,42.300003,0.0,135.0,62.699997,1.116,1.0,2023-06-16 17:45:00
35880,144.73999,159.48001,71.130005,77.19,29.460000,31.680000,1065.7400,520.04004,145.35,163.69000,...,2.449294e-16,-2.0,128.0,28.400000,0.0,100.0,42.000000,0.742,1.0,2023-06-16 18:00:00

In [27]:
#n_df.reset_index(inplace=True)
n_df.reset_index(inplace=True)

In [16]:
tmp_df.to_csv("./data/comm_code_filtered.csv", sep=";", index=False)

In [30]:
for col in n_df:
    if any(key in col for key in "CommunicationCode"):
        t_df[col]= n_df[col]
    else:
        pass

In [31]:
t_df.head()

,INV03_CurrentDC(A),INV03_CurrentAC(A),INV03_PowerAC(kW),INV03_PowerDC(kW),INV03_InternalTemperature(C),INV03_HeatSinkTemperature(C),INV03_VoltageDC(V),INV03_VoltageAC(V),INV02_CurrentDC(A),INV02_CurrentAC(A),...,soil_temperature_7_to_28cm (Â°C),soil_moisture_7_to_28cm (mÂ³/mÂ³),isday,timestamp,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,51.8,0.364,0.0,2022-06-08 00:00:00,0,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77.7,0.546,0.0,2022-06-08 00:15:00,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77.7,0.546,0.0,2022-06-08 00:30:00,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77.7,0.546,0.0,2022-06-08 00:45:00,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76.8,0.546,0.0,2022-06-08 01:00:00,0,0,0,0,0,0

In [32]:
t_df["INV02_CommunicationCode_60"] = t_df["INV02_CommunicationCode_60"].astype(int)
t_df["INV02_CommunicationCode_116"] = t_df["INV02_CommunicationCode_116"].astype(int)
t_df["INV03_CommunicationCode_60"] = t_df["INV03_CommunicationCode_60"].astype(int)
t_df["INV03_CommunicationCode_116"] = t_df["INV03_CommunicationCode_116"].astype(int)
t_df["Cont_CommunicationCode_60"] = t_df["Cont_CommunicationCode_60"].astype(int)
t_df["Cont_CommunicationCode_118"] = t_df["Cont_CommunicationCode_118"].astype(int)

In [33]:
t_df.to_csv("./data/merged_annuale_meteo_sunrise_filtrato15_comm_code.csv", sep=";", index=False)

In [39]:
df = pd.read_csv("./data/merged_annuale_meteo_sunrise_filtrato15_comm_code.csv", delimiter=";")

In [40]:
df.head()

,INV03_CurrentDC(A),INV03_CurrentAC(A),INV03_PowerAC(kW),INV03_PowerDC(kW),INV03_InternalTemperature(C),INV03_HeatSinkTemperature(C),INV03_VoltageDC(V),INV03_VoltageAC(V),INV02_CurrentDC(A),INV02_CurrentAC(A),...,soil_temperature_7_to_28cm (Â°C),soil_moisture_7_to_28cm (mÂ³/mÂ³),isday,timestamp,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,51.8,0.364,0.0,2022-06-08 00:00:00,0,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77.7,0.546,0.0,2022-06-08 00:15:00,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77.7,0.546,0.0,2022-06-08 00:30:00,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,77.7,0.546,0.0,2022-06-08 00:45:00,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76.8,0.546,0.0,2022-06-08 01:00:00,0,0,0,0,0,0

In [27]:
print(df.INV02_CommunicationCode_60.unique())
print(df.INV02_CommunicationCode_116.unique())
print(df.INV03_CommunicationCode_60.unique())
print(df.INV03_CommunicationCode_116.unique())
print(df.Cont_CommunicationCode_60.unique())
print(df.Cont_CommunicationCode_118.unique())

[0 1]
[0]
[0 1]
[0]
[0 1]
[0 1]

In [ ]:
df.drop(columns=["timestamp"], inplace = True)
scaler = MinMaxScaler().fit(df)
train_data = scaler.transform(df)

In [ ]:
df.head()

,INV03_CurrentDC(A),INV03_CurrentAC(A),INV03_PowerAC(kW),INV03_PowerDC(kW),INV03_InternalTemperature(C),INV03_HeatSinkTemperature(C),INV03_VoltageDC(V),INV03_VoltageAC(V),INV02_CurrentDC(A),INV02_CurrentAC(A),...,cloudcover (%),soil_temperature_7_to_28cm (Â°C),soil_moisture_7_to_28cm (mÂ³/mÂ³),isday,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,42.0,51.8,0.364,0.0,0,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.0,77.7,0.546,0.0,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.0,77.7,0.546,0.0,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.0,77.7,0.546,0.0,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,45.0,76.8,0.546,0.0,0,0,0,0,0,0

In [ ]:
print(df.INV02_CommunicationCode_60.unique())
print(df.INV02_CommunicationCode_116.unique())
print(df.INV03_CommunicationCode_60.unique())
print(df.INV03_CommunicationCode_116.unique())
print(df.Cont_CommunicationCode_60.unique())
print(df.Cont_CommunicationCode_118.unique())

[0 1]
[0]
[0 1]
[0]
[0 1]
[0 1]

In [ ]:
df["INV02_CommunicationCode_60"]

0        0
1        0
2        0
3        0
4        0
        ..
35876    0
35877    0
35878    0
35879    0
35880    0
Name: INV02_CommunicationCode_60, Length: 35881, dtype: int64

In [44]:
df.set_index("timestamp", inplace=True)

In [52]:
df.head()

,INV03_CurrentDC(A),INV03_CurrentAC(A),INV03_PowerAC(kW),INV03_PowerDC(kW),INV03_InternalTemperature(C),INV03_HeatSinkTemperature(C),INV03_VoltageDC(V),INV03_VoltageAC(V),INV02_CurrentDC(A),INV02_CurrentAC(A),...,cloudcover (%),soil_temperature_7_to_28cm (Â°C),soil_moisture_7_to_28cm (mÂ³/mÂ³),isday,INV02_CommunicationCode_60,INV02_CommunicationCode_116,INV03_CommunicationCode_60,INV03_CommunicationCode_116,Cont_CommunicationCode_60,Cont_CommunicationCode_118
timestamp,,,,,,,,,,,,,,,,,,,,,
2022-06-08 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,42.0,51.8,0.364,0.0,0,0,0,0,0,0
2022-06-08 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.0,77.7,0.546,0.0,0,0,0,0,0,0
2022-06-08 00:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.0,77.7,0.546,0.0,0,0,0,0,0,0
2022-06-08 00:45:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,63.0,77.7,0.546,0.0,0,0,0,0,0,0
2022-06-08 01:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,45.0,76.8,0.546,0.0,0,0,0,0,0,0

In [51]:
print(df["2022-07-10 08:00:00"].iloc["INV03_CommunicationCode_60"])

KeyError: '2022-07-10 08:00:00'